### ISSUE TITLE
Print like an "it" block in interactive mode

### ISSUE THREAD

**Issue by R-Bower** [filiphric/cypress-plugin-steps#13]
Cool plugin!  I'm coming from playwright and miss its individual test steps.  They're a great way to organize tests without having to declare a completely separate test.

Is it possible to output the step at the top level of the spec viewer in interactive mode?

Here's a screenshot of what I mean:
![image](https://user-images.githubusercontent.com/11933208/229691402-0b391718-b5a4-4154-a7b3-b3b0c0f30c35.png)

I'm not sure if this is possible, but if so it'd be nice.

**Comment by filiphric** [comment]
this would be quite hard. Cypress folds each test after it runs, and hides all command. I would need to somehow interfere with this. plus, at the time `cy.step()` is called, there’s no way for me to know whether that step is successful or not. I would need to add additional logic to it, that would add a ✅  or ❌  to every step.

I theory, I think it could be done, with a looot of hacking, but this is just a hobby project and I don’t think the time investment is worth it.
