### ISSUE TITLE
Cannot call cy.step() outside a running test

### ISSUE THREAD

**Issue by csmith0289** [filiphric/cypress-plugin-steps#16]
Could this be adapted and extended in any way so that cy.step and cy.section could be called from the POM.
It would be nice to avoid duplication of cy.step in the test and have these moved into the method within the page object.

**Comment by csmith0289** [comment]
Closed found another task asking if anything cy.* can be called outside of it() or cypress hooks and the answer was no.
Closing this for that reason, but I think it would have been nice to have and make it reusable.

**Comment by csmith0289** [comment]
@filiphric Sorry to bother you, but im wondering if this could be make to work in a POM structure? I closed this originally, but its playing on me that i've not asked and maybe I was looking at the wrong information.
So do you know if we can somehow run cy.steps from POM outside of the it() blocks technically possibly by moving it to a cy.task or something like that?

**Comment by filiphric** [comment]
can you give me a code example? I am not sure I understand. you can only run cy commands inside it() blocks. even if you have a page object, that still needs to run its methods inside a test, so I am not sure what kind of implementation you are trying to aim for

**Comment by csmith0289** [comment]
export class editPage extends BasePage {

    clickSaveButton() {
        cy.get(saveButton, { timeout: 15000 }).should('be.visible').click()
        super.veryfiLoadingBarNotVisible()
    }
    
    So assume we have this page object for the editPage
    
    Currently to run the steps, we need to add cy.step('Clicking Save Button) in the test.
    
    I just want to confirm if there was a way of putting the cy.step command in the method clickSaveButton
    and not in the test.
    
    So each time the method clickSaveButton is called in a test, it automatically has the cy.step there.
    I don't think there is a way, but just wanted to make sure.

**Comment by filiphric** [comment]
I think for your case, you can make it part of the method, unless you don’t want to do that for some reason
```js
export class editPage extends BasePage {
clickSaveButton() {
    cy.step('Clicking Save Button')
    cy.get(saveButton, { timeout: 15000 }).should('be.visible').click()
    super.veryfiLoadingBarNotVisible()
}
```

**Comment by csmith0289** [comment]
I'll give it another go, I'm sure if tried this but it errored with the reason 'Cannot call cy.step() outside a running test' but there maybe a chance I'd put the command outside a test and in the description possibly, but I couldn't see if initially.
I appreciate you getting back to me and so quickly.

**Comment by csmith0289** [comment]
Yeah that's an PICNIC (problem is in chair not in computer) issue I did have a cy.step outside of the test.
Removing that and adding cy.step into the method is working as expected.
