### ISSUE TITLE
What happens if you have used CY Step in your test and the library is not installed

### ISSUE THREAD

**Issue by Alan-Carr** [filiphric/cypress-plugin-steps#17]
If a user adds CY Step to  a script and the test is then used  via CLI on a machine where the library is not installed is that a problem ?

**Comment by filiphric** [comment]
yes, you need to install the plugin in order for cy.step() command to work

**Comment by Alan-Carr** [comment]
Yes I have the plugin installed on the machine where I develop my tests, however  if you run that same script using CLI (with cy.step commands) on another machine after you have done all your initial debugging that doesn't have cy.step installed will the script still run or would i need to install or comment out the cy.step commands.
