### ISSUE TITLE
Make cypress-plugin-steps work with cypress-terminal-report plugin

### ISSUE THREAD

**Issue by didlika** [filiphric/cypress-plugin-steps#2]
At the moment two cypress-terminal-report is not showing sections nor steps 
Link to cypress-terminal-report plugin -> https://www.npmjs.com/package/cypress-terminal-report?activeTab=versions

![image](https://user-images.githubusercontent.com/80490488/220604857-fbfe4f2b-147b-4d18-bfdd-edb5ea1e811a.png)

**Comment by filiphric** [comment]
released in `v1.1.0`
