### ISSUE TITLE
Cypress-plugin-steps don't work properly with cy.origin command

### ISSUE THREAD

**Issue by yoandrisespinosa** [filiphric/cypress-plugin-steps#3]
Description problem:
- According cypress-plugin-steps docs  works similarly to cy.log() command. However it does not work properly when run with the cy.origin command.

![image](https://user-images.githubusercontent.com/89758543/220780570-29ccecf0-e8f5-46a3-92a2-7e1d9aff75ef.png)

Why is this needed?
it is necessary to continue with the numbering of the steps within the cy.origin command.

**Comment by filiphric** [comment]
Not much I can do here, I’m limited with Cypress `cy.origin()` functionality. Theoretically, it could work by adding `experimentalOriginDependencies: true` to your `cypress.config.js` and then using `Cypress.require('cypress-plugin-steps')` inside `cy.origin()` command [as mentioned in the docs](https://docs.cypress.io/api/commands/origin#Dependencies--Sharing-Code), but I’m not 100% sure about the solution
