### ISSUE TITLE
cy.section() and cy.step() doesn't work in before() section 

### ISSUE THREAD

**Issue by BriceCast** [filiphric/cypress-plugin-steps#8]
Maybe I miss something in doc but I see that the two new commands are not working in spec before() section.
Looking at the code it seems consistent as "testFlow" is introduced in the beforeEach. But In our case we use some customs methods/helpers, very close to actions/prerequisites in Gherkins, so callable both in a test or a global pre-requisite.
Do you think it would be possible to make it work in before() ?
Thanks

![image](https://user-images.githubusercontent.com/125866814/221835676-325bafff-41b4-455a-93f3-50c353e90f9a.png)

**Comment by didlika** [comment]
They work with beforeEach so I guess they should also work with before hook.

**Comment by filiphric** [comment]
Yup, this may be by design right now, but I'll make an update for this so it works ok in before hook as well

**Comment by BriceCast** [comment]
Thank for the answer. I fix it on my side by separating logs that come from the before from the others. And considering that before logs belong to all scenarios and should be used for each error messages. I can share it with you if you need.

**Comment by Karpenko3d** [comment]
I started getting the following error as well: 

![image-Vy8eRv7e-2023@2x](https://user-images.githubusercontent.com/55722182/222516557-d5986a44-1e7f-4895-aa3e-23fb6d8b2633.png)
